### ISSUE TITLE
Do you have any chance to version up this library? 

### ISSUE THREAD

**Issue by Kazuuk** [spotfiresoftware/spotfire-sbdf-c#8]
Hello.

I'm studying about the Spotfire SBDF file format these days, and found this C library and Python library.
When I convert CSV file to SBDF file format with both libraries, C library result file and Python library result file is not the same file size.
I looked into both files, C library result looks like the list of the all elements, but Python library result files looks like compressed elements.
I usually make program by C++, so I wonder if "spotfire-sbdf-c" library will going to version up or not.
And if you are not planning to version up this library, only Python library will keep updated? 

With regards,
Insub Hwang.

**Comment by bbassett-tibco** [comment]
Hi, @Kazuuk!  We currently don't have any plans to release new versions of this repository, but that's mainly due to not having any outstanding items that requires such a release.  Most of our issues in `spotfire-python` are more about supporting Python than dealing with SBDF files.  (`spotfire-python` is more than just a Python interface for SBDF; this repository only deals with the SBDF processing.)

As for your note about compressed elements being generated by the Python module, that was actually one of the main reasons we rearchitected the Python module to use the C library to create SBDF files.  The key is to use RLE encoding ([`SBDF_RUNLENGTHENCODINGTYPEID`](https://github.com/spotfiresoftware/spotfire-sbdf-c/blob/8a99c83793c8c49439bb11d0eaf732b1ee906160/include/valuearray.h#L20)) when creating the `sbdf_valuearray` structure with the `sbdf_va_create` function.

Thanks for your interest in the codebase,
Brian

**Comment by Kazuuk** [comment]
Hello, @bbassett-tibco!

Thank you for the fast reply.
I make sbdf file with "SBDF_RUNLENGTHENCODINGTYPEID" you told me, then the size of the sbdf file is a little bit smaller than Python result!
It is maybe I didn't write table metadata, but I surprised that C library already has the solution in it!
I'm so fool to used only the example code to make sbdf! Lol~
Now I don't have to make multi-language in one program at all!
I hope you have a nice days!

+ By the way, when I made a C program with this, near from 697980 or over line is not working properly.
   I have no idea about the problem so far. Do you have an idea which cause this?

Best regards,
Insub Hwang

**Comment by bbassett-tibco** [comment]
Don't feel bad about having to depend on examples for information on the library and the data format itself.  I acknowledge that we don't have very much documentation available for either.

It's likely the size difference you're seeing is the table metadata as you hypothesize, but I would recommend to not leave it out due to three bits of information that are embedded in the metadata that are required by Spotfire and other SBDF importers (like the Python module) to read the SBDF file:
* number of columns
* column types (in the column metadata)
* column names (in the column metadata)

As for the not working after a certain point, I think the issue here is that every so often, you need to start a new table slice.  Our uses of this library typically do this approximately every 100,000 values.  For example, if you had a three column (call them columns 'A', 'B', and 'C') by 50,000 row table, you would end up with the following sections in the exported SBDF file:
* file header
* table metadata
* table slice
* column slice for column 'A' rows 1-33,333
* column slice for column 'B' rows 1-33,333
* column slice for column 'C' rows 1-33,333
* table slice
* column slice for column 'A' rows 33,334-50,000
* column slice for column 'B' rows 33,334-50,000
* column slice for column 'C' rows 33,334-50,000
* end of table

You can see this behavior in the Python module at https://github.com/spotfiresoftware/spotfire-python/blob/main/spotfire/sbdf.pyx#L1847-L1911 (although this is written in Cython, it hews closely to the C API provided by this library, and should illustrate the technique).

**Comment by Kazuuk** [comment]
Your answer, that slicing is the key, really helps me !
I changed my code split table in 100k rows and * 1k slices, then 100 million rows perfectly printed !

Now I'm heading on the problem that when I add more columns in the table, SBDF file size is getting bigger than CSV.
Does SBDF file format is best fit for the large row data?
If is that so, is there any other way or file format that can reduce large column data?

I'm really sorry that I bother you so long, but thank you all the time when I'm make the program with this library. :)

**Comment by bbassett-tibco** [comment]
Good to hear that you're having success.  Don't worry about bothering me; having an external user ask questions goes a long way to identifying points that we need to cover when we get around to adding documentation for the C library's API.

As far as file size or suitability goes, I guess that the answer is "it depends".  SBDF was designed as a high-fidelity way of representing data in a Spotfire analysis document, including different data types and missing values; it's binary to avoid precision loss involved with things like converting floating point numbers to and from strings.  It's not trying to be optimally sized in relation to other formats.  I don't think I can provide any advice on alternatives.

**Comment by Kazuuk** [comment]
Thank you for your kind answers all the time !
I understand that the SBDF file format is not for the data size, but for the precise data and the performance.
My question might be end for now. :)
If I have any problem using this library I will contact you later.
You really helped me a lot ! 👍👍👍👍 
I hope you have a nice days ! Ciao~
